### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by DeadUSB**
blog support

### CODE REVIEW

**Comment by devkarthin** [comment]
Bro forgot to `git pull`

**Comment by DeadUSB** [comment]
nuh uh

**Comment by devkarthin** [comment]
Your pull request will never be merged.

**Review by devkarthin — CHANGES_REQUESTED** [review]
Git pull rebase and force push plz

**Comment by devkarthin** [comment]
Closed without comment. Bro got absolutely OWNED!!

**Pull request closed without merging**
